version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rozx_local
      POSTGRES_USER: rozx_database_local
      POSTGRES_PASSWORD: Shivam1257
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  migration:
    build:
      context: .
      target: builder
    container_name: migration
    env_file:
      - .env.docker
    depends_on:
      postgres:
        condition: service_healthy
    command: npx prisma migrate deploy

  api:
    build:
      context: .
      target: runner
    container_name: api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      migration:
        condition: service_completed_successfully

volumes:
  postgres_data:
  redis_data:
